### ISSUE TITLE
Key sequence s-m p starts with non-prefix                                                                                    |  define-key

### ISSUE THREAD

**Issue by peng051410** [daedreth/UncleDavesEmacs#1]
I use this config, When i run emacs, I got an error:
![image](https://user-images.githubusercontent.com/5512326/35842012-8c66c626-0b3a-11e8-9a8a-3f56d840d1ad.png)
mac version:10.13.3 
emacs version:GNU Emacs 25.3.1

What should i do ?

**Comment by daedreth** [comment]
Did you set s-m to a function before? It sure as hell doesn't happen for me.
s-m is not defined in my configuration, try getting rid of the emms keybindings and see what s-m stands for.

**Comment by peng051410** [comment]
Yes, the key in my system already used by other software! thank you!
