### ISSUE TITLE
Firefox in Emacs?

### ISSUE THREAD

**Issue by NatHarari** [daedreth/UncleDavesEmacs#13]
Hi there,

This isn't an "issue" per se, but I can't find any other way of contacting you. I've been watching your video from a year ago on Emacs (I'm a new Spacemacs user), and I saw that at the beginning of the video, you ran Firefox in Emacs.
Could you please let me know how you did that? That would be fantastic if I could do the same.

Thanks very much, and your config file is a really wonderful learning tool.

**Comment by yisraeldov** [comment]
Exwm

**Comment by NatHarari** [comment]
Thank you! :) Todah rabah.
