### ISSUE TITLE
Unable to open files

### ISSUE THREAD

**Issue by x61** [daedreth/UncleDavesEmacs#2]
I am using your fork but I am unable to open files from the terminal. For example, if I type `emacs tests.txt`, it does not open the text file. I am using mac. Is there a setting somewhere to address this?

**Comment by daedreth** [comment]
"does not open the text file"
How exactly? Is emacs still launched? Is there an error in the *Messages* buffer? Is emacs already running in the background?

See what happens if you launch emacs and then in a terminal do `emacsclient tests.txt`

Also make sure to pull the latest changes, emacs-server starts by default now.

**Comment by x61** [comment]
No error message shows up. Just the emacs scratch. `emacsclient tests.txt` does not open. It just shows the emacs scratch window. Once I delete the `.emacs.d` directory, I am able to open files with `emacs tests.txt`. I like your setting and would like to use it as a base for my emacs but it is very difficult to use it when it is difficult to open files. Do you know if there is a setting somewhere that needs to be set? I am using mac and emacs version 25 also using zshell.

**Comment by daedreth** [comment]
this is very odd behaviour, it does not happen on GNU/Linux or on Windows, I will ask around for folks using MacOS and see if I can find the cause.

What happens if you launch emacs normally and then C-x C-f to find and open a file?

**Comment by x61** [comment]
Actually, C-x C-f does not open files either. 

UPDATE:
I just cloned this on my Ubuntu environment and I am still unable to open files with `emacs fileName`.  When emacs starts, with and without `fileName`, it asks `Replace existing window manager? (y or n)`.  I said, no because I do not want to replace my window manager. Regardless, the `fileName` never opens. Not even with `C-x C-f`.

**Comment by daedreth** [comment]
I just tested on 2 gnu/linux machines and on windows, it works flawlessly and honestly I have no idea what could be causing this.

**Comment by x61** [comment]
Thanks very much. This is the message I get when emacs first starts after cloning `Warning (emacs): [EXWM] EXWM fails to start (void-function: (class-v))`. Is there way to exclude EXWM from the config? Possibly without deleting it. 

Also, each time I start emacs it asks if I want to `Replace existing window manager? (y or n)`. when I say `n`, it displays `Warning (emacs): [EXWM] EXWM fails to start (error: (Other window manager detected))`

**Comment by daedreth** [comment]
Find `(exwm-enable)` and delete it, see if it helps

**Comment by x61** [comment]
EXCELLENT. Works now on Ubuntu. Going try again later on my mac and report back. Thanks very much.

**Comment by daedreth** [comment]
Great, let me know how it fares under OSX

**Comment by x61** [comment]
Commenting out `(exwm-enable)` in the config resolved the issue under OSX as well. Thanks for the help. 

Great config, by the way.
