### ISSUE TITLE
Key sequence s-m p starts with non-prefix key s-m Warning (initialization)

### ISSUE THREAD

**Issue by peng051410** [daedreth/UncleDavesEmacs#3]
Hello, I use you config to starup, got error:
`Error (use-package): emms/:catch: Key sequence s-m p starts with non-prefix key s-m
Warning (initialization): An error occurred while loading ‘/Users/tomyli/.emacs.d/init.el’:`
What should i do?

**Comment by daedreth** [comment]
Allow me to guess.
macOS?

**Comment by peng051410** [comment]
Yes！

**Comment by daedreth** [comment]
~~use a normal operating system~~

Look for s-m p in the config.org (it's at the very bottom, in the EMMS section) and *either*:
- Delete it, in case you won't be using emms
- Change it to something that doesn't trip over default OSX keybindings.

If you don't plan on using emacs to control mpd, you can get rid of the entire emms section!

**Comment by peng051410** [comment]
I already delete it! thanks!

**Comment by peng051410** [comment]
I find that I've already mentioned this before.😄
