### ISSUE TITLE
Rainbow-delimiters but no show-paren-mode?

### ISSUE THREAD

**Issue by borgauf** [daedreth/UncleDavesEmacs#4]
This isn't an "issue" per se, but I don't know how to contact you otherwise. Anyway, I'm going through your config/init and I don't see you actually turning on paren-matching although I do see rainbow-delimiters. So a quick (show-paren-mode 1) turns things on. I guess I'm curious why you've got rainbow-delimiters but don't turn paren matching on?

**Comment by daedreth** [comment]
Mustve forgotten about it when I ported my config to org, thanks for reminding!
Fixed in latest commit
