### ISSUE TITLE
table alignment 

### ISSUE THREAD

**Issue by Neocurve** [daedreth/UncleDavesEmacs#6]
Hi, 
I have followed your youtube tutorial for emacs and was great. I have one problem with org mode table alignment. I have used your complete emacs config on Mac, Windows, and Ubuntu. I have same problem for all. the html output is fine as you can see on attached, but alignment is strange on org mode. can you please advise ?
<img width="263" alt="org-mode" src="https://user-images.githubusercontent.com/19428432/40135693-3826fb62-5946-11e8-85d5-0c29c2c69ca4.png">
<img width="294" alt="html" src="https://user-images.githubusercontent.com/19428432/40135694-38422554-5946-11e8-9698-3aa7f5fc4e8b.png">
Many thanks in advance.

**Comment by daedreth** [comment]
Do you switch between cells inside the table using Tab?
If not, this could cause this issue I guess

**Comment by Neocurve** [comment]
Yes, I did. This is very strange. and I don't know why the html output has a line on the top table and html file has nice arrangement.

**Comment by daedreth** [comment]
Not gonna lie, no idea what could cause this.

**Comment by Neocurve** [comment]
I found the issue. Font was the problem. I deleted all font setting and seems fine.
Thanks you
